sudo: false
cache:
  - pip
  - directories:
    - $HOME/.cache/pip
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - KicadModTree/manage.sh update_dev_packages
script:
  - KicadModTree/manage.sh pep8_check
  - KicadModTree/manage.sh unit_tests
