base:
    package: TO-252
    keywords: 'the quick brown fox'
    footprint:
        x_mm: 10.6
        tab_x_mm: 6.4
        tab_y_mm: 5.8
        split_paste: 'off'
        paste_gutter_mm: 0.3
    device:
        x_mm: 9.9
        body:
            x_mm: 6.22
            y_mm: 6.5
        tab:
            x_mm: 1.0
            y_mm: 5.4
    3d_prefix: '${KISYS3DMOD}/TO_SOT_Packages_SMD.3dshapes'
variants:
    - pins: 3
      pitch: 2.28
      pad:
          x_mm: 2.2
          y_mm: 1.2
      centre_pin: ['cut', 'uncut']
      keywords: 'jumped over the'
      datasheet: http://www.molex.com/pdm_docs/sd/555600307_sd.pdf
    - pins: 5
      pitch: 1.34
      pad:
          x_mm: 2.2
          y_mm: 0.8
      centre_pin: ['cut', 'uncut']
      keywords: 'lazy dog'
      datasheet: http://www.molex.com/pdm_docs/sd/555600307_sd.pdf

---

base:
    package: TO-263
    keywords: 'the quick brown fox'
    footprint:
        x_mm: 16.15
        tab_x_mm: 9.4
        tab_y_mm: 10.8
        split_paste: 'on'
        paste_gutter_mm: 0.3
    device:
        x_mm: 15.0
        body:
            x_mm: 9.25
            y_mm: 10.0
        tab:
            x_mm: 1.0
            y_mm: 10.0
    3d_prefix: '${KISYS3DMOD}/TO_SOT_Packages_SMD.3dshapes'
variants:
    - pins: 3
      pitch: 2.54
      pad:
          x_mm: 4.6
          y_mm: 1.1
      centre_pin: ['cut', 'uncut']
      keywords: 'jumped over the'
      datasheet: http://www.molex.com/pdm_docs/sd/555600307_sd.pdf
    - pins: 5
      pitch: 1.7
      pad:
          x_mm: 4.6
          y_mm: 1.1
      centre_pin: ['cut', 'uncut']
      keywords: 'lazy dog'
      datasheet: http://www.molex.com/pdm_docs/sd/555600307_sd.pdf
    - pins: 7
      pitch: 1.27
      pad:
          x_mm: 4.6
          y_mm: 0.8
      centre_pin: ['cut', 'uncut']
      keywords: 'lazy dog'
      datasheet: http://www.molex.com/pdm_docs/sd/555600307_sd.pdf

---

base:
    package: TO-268
    keywords: 'the quick brown fox'
    footprint:
        x_mm: 21.95
        tab_x_mm: 13.5
        tab_y_mm: 16.6
        split_paste: 'on'
        paste_gutter_mm: 0.3
    device:
        x_mm: 19.0
        body:
            x_mm: 14.0
            y_mm: 15.9
        tab:
            x_mm: 1.1
            y_mm: 15.9
    3d_prefix: '${KISYS3DMOD}/TO_SOT_Packages_SMD.3dshapes'
variants:
    - pins: 3
      pitch: 5.45
      pad:
          x_mm: 5.0
          y_mm: 3.0
      centre_pin: ['cut']
      keywords: 'jumped over the'
      datasheet: http://www.molex.com/pdm_docs/sd/555600307_sd.pdf

