# SMD trimmer capacitors STYLE A
base:
    family: STYLE-A
    description: 'trimmer capacitor SMD'
    keywords: ''
    device:
        body:
            colour: 'white body'
        frame:
            colour: 'metal grey pins'
        contacts:
            colour: 'metal grey pins'
        cover:
           colour: 'white body'
        rotor:
           colour: 'white body'
    3d_prefix: '${KISYS3DMOD}/Capacitors_SMD.3dshapes'
variants:
    - series: TZR1
      manufacturer: Murata
      footprint:
          x_mm: 2.2
          pad:
              x_mm: 0.5
              y_mm: 0.5
      device:
          body:
              x_mm: 1.7
              y_mm: 1.4
          chamfer:
              sides: []
              size_mm: 0.0
          projection: 
              sides: ['x', 'y']
              offset_mm: 0.1
              x_side_mm: 0.9
              y_side_mm: 0.6
      keywords: ''
      datasheet: http://www.infineon.com/cms/en/product/packages/PG-TO252/PG-TO252-3-1/
    - series: TZY2
      manufacturer: Murata
      footprint:
          x_mm: 4.0
          pad:
              x_mm: 0.8
              y_mm: 1.2
      device:
          body:
              x_mm: 3.0
              y_mm: 2.1
          chamfer:
              sides: []
              size_mm: 0.0
          projection: 
              sides: ['x', 'y']
              offset_mm: 0.2
              x_side_mm: 1.8              
              y_side_mm: 1.0
      keywords: ''
      datasheet: http://www.infineon.com/cms/en/product/packages/PG-TO252/PG-TO252-3-1/
    - series: TZW4
      manufacturer: Murata
      footprint:
          x_mm: 7.0
          pad:
              x_mm: 1.3
              y_mm: 2.5
      device:
          body:
              x_mm: 5.2
              y_mm: 4.0
          chamfer:
              sides: []
              size_mm: 0.0
          projection: 
              sides: ['x']
              offset_mm: 0.1
              x_side_mm: 3.0
              y_side_mm: 0.0
      keywords: ''
      datasheet: http://www.infineon.com/cms/en/product/packages/PG-TO252/PG-TO252-3-1/
    - series: JR
      manufacturer: Voltronics
      footprint:
          x_mm: 4.4
          pad:
              x_mm: 1.0
              y_mm: 1.8
      device:
          body:
              x_mm: 3.5
              y_mm: 3.1
          chamfer:
              sides: ['left']
              size_mm: 0.6
          projection: 
              sides: ['y']
              offset_mm: 0.4
              x_side_mm: 0.0
              y_side_mm: 1.6
      keywords: ''
      datasheet: http://www.infineon.com/cms/en/product/packages/PG-TO252/PG-TO252-3-1/
---

